### ISSUE TITLE
trace dies in Controller when using the helptext document to setup the mouse callback

### ISSUE THREAD

**Issue by olyoberdorf** [GeminiDRSoftware/DRAGONS#245]
This may be an easy fix in the order of initializing the trace view (i.e. helptext first).

trace is issuing a much uglier trace after the “Safari trace”.
   error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'mousemove', 'event_values': {'sx': 151, 'sy': 5, 'x': 172.4660194174758, 'y': 664.3923510235549}}}], 'references': []} 
 error: AttributeError("'NoneType' object has no attribute 'add_timeout_callback'")
Traceback (most recent call last):
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/document/document.py", line 398, in apply_json_patch
    self._trigger_on_message(event_json["msg_type"], event_json["msg_data"])
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/document/document.py", line 687, in _trigger_on_message
    cb(msg_data)
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/document/document.py", line 356, in apply_json_event
    model._trigger_event(event)
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 91, in _trigger_event
    self._document._with_self_as_curdoc(invoke)
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/Users/klabrie/condaenvs/susd3_dev_20200710/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 80, in invoke
    callback(event)
  File "/data/GemKLRepo/dragons3.7/geminidr/interactive/controls.py", line 220, in on_mouse_move
    self.handle_mouse(self.x, self.y)
  File "/data/GemKLRepo/dragons3.7/geminidr/interactive/controls.py", line 292, in handle_mouse
    self.helptext.document.add_timeout_callback(self.handle_mouse_callback, 100)
AttributeError: 'NoneType' object has no attribute 'add_timeout_callback'
5:41
And I don’t know if it is related, the storeScience that follows it does not seem to write the 2D stack it is requested to write.

**Comment by KathleenLabrie** [comment]
FYI, it is not related to the `storeScience` behavior.
