### ISSUE TITLE
Crash in adjustWCSToReference on GSAOI data

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#391]
I get the error below when I run the integration test.  When I start with the astrometryCorrected files, and call `adjustWCSToReference` directly, it does not crash.   I am not able to reproduce this on a small scale.  I'll keep trying to find a combination that does not take ages to run and can reproduce this issue.  (I can reproduce at will with the integration test, takes a long time to run.)

Posting this now in case the error means something to someone.

`release/3.1.x` branch

```   
PRIMITIVE: adjustWCSToReference
   -------------------------------
   Cross-correlating sources between S20150605S0266_astrometryCorrected.fits and S20150605S0265_astrometryCorrected.
fits
   Coarse model in 0.41 seconds
   offset: -20.003726637143473
   offset: -0.15876510652196307
   
   Final model in 0.47 seconds
   offset: -20.047873267732772
   offset: -0.10530124429581791
   
   WARNING - Too few correlated sources (1). Cannot adjust WCS.
   Cross-correlating sources between S20150605S0267_astrometryCorrected.fits and S20150605S0265_astrometryCorrected.
fits
   Coarse model in 0.39 seconds
   offset: -23.24549668002686
   offset: -22.76297912430053
   
   Final model in 0.44 seconds
   offset: -23.24549668002686
   offset: -22.76297912430053
   
   WARNING - Too few correlated sources (0). Cannot adjust WCS.
   Cross-correlating sources between S20150605S0268_astrometryCorrected.fits and S20150605S0265_astrometryCorrected.
fits
   Coarse model in 0.43 seconds
   offset: -3.2414278077087317
   offset: -23.00412622817487
   
   Final model in 0.49 seconds
   offset: -3.2414278077087317
   offset: -23.00412622817487
   
   Cross-correlating sources between S20150605S0269_astrometryCorrected.fits and S20150605S0265_astrometryCorrected.fits
   Coarse model in 0.41 seconds
   offset: -3.4839434287504787
   offset: -43.01015012921414
   
   Final model in 0.46 seconds
   offset: -3.4839434287504787
   offset: -43.01015012921414

ERROR - Reduce received an unhandled exception. Aborting ...
ERROR - Traceback (most recent call last):
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/reduction/coreReduce.py", line 246, in runr
ERROR -     recipe(p)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/geminidr/gsaoi/recipes/sq/recipes_IT.py", line 25, in reduceit
ERROR -     p.adjustWCSToReference()
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/utils/decorators.py", line 364, in gn
ERROR -     ret_value = fn(pobj, adinputs=adinputs, **fnargs)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/utils/decorators.py", line 293, in gn
ERROR -     ret_value = fn(pobj, **kwargs)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/geminidr/gsaoi/primitives_gsaoi_image.py", line 123, in adjustWCSToReference
ERROR -     objcat = merge_gsaoi_objcats(ad, cull_sources=cull_sources)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/geminidr/gsaoi/primitives_gsaoi_image.py", line 562, in merge_gsaoi_objcats
ERROR -     return table.vstack(objcats, metadata_conflicts='silent')
ERROR -   File "/home/pipetest/testconda/susd3.9_20220816-test/lib/python3.9/site-packages/astropy/table/operations.py", line 646, in vstack
ERROR -     tables = _get_list_of_tables(tables)  # validates input
ERROR -   File "/home/pipetest/testconda/susd3.9_20220816-test/lib/python3.9/site-packages/astropy/table/operations.py", line 53, in _get_list_of_tables
ERROR -     raise ValueError('no values provided to stack.')
ERROR - ValueError: no values provided to stack.
Writing final outputs ...
        Wrote S20150605S0265_astrometryCorrected.fits in output directory
        Wrote S20150605S0266_astrometryCorrected.fits in output directory
        Wrote S20150605S0267_astrometryCorrected.fits in output directory
        Wrote S20150605S0268_astrometryCorrected.fits in output directory
        Wrote S20150605S0269_astrometryCorrected.fits in output directory
        Wrote S20150605S0270_sourcesDetected.fits in output directory
ERROR - reduce caught an unhandled exception.
ERROR - 
ERROR - no values provided to stack.
ERROR - Traceback (most recent call last):
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/scripts/reduce", line 87, in main
ERROR -     r_reduce.runr()
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/reduction/coreReduce.py", line 246, in runr
ERROR -     recipe(p)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/geminidr/gsaoi/recipes/sq/recipes_IT.py", line 25, in reduceit
ERROR -     p.adjustWCSToReference()
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/utils/decorators.py", line 364, in gn
ERROR -     ret_value = fn(pobj, adinputs=adinputs, **fnargs)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/recipe_system/utils/decorators.py", line 293, in gn
ERROR -     ret_value = fn(pobj, **kwargs)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/geminidr/gsaoi/primitives_gsaoi_image.py", line 123, in adjustWCSToReference
ERROR -     objcat = merge_gsaoi_objcats(ad, cull_sources=cull_sources)
ERROR -   File "/pipetest/IT/testco/dragons/testbranch/geminidr/gsaoi/primitives_gsaoi_image.py", line 562, in merge_gsaoi_objcats
ERROR -     return table.vstack(objcats, metadata_conflicts='silent')
ERROR -   File "/home/pipetest/testconda/susd3.9_20220816-test/lib/python3.9/site-packages/astropy/table/operations.py", line 646, in vstack
ERROR -     tables = _get_list_of_tables(tables)  # validates input
ERROR -   File "/home/pipetest/testconda/susd3.9_20220816-test/lib/python3.9/site-packages/astropy/table/operations.py", line 53, in _get_list_of_tables
ERROR -     raise ValueError('no values provided to stack.')
ERROR - ValueError: no values provided to stack.
ERROR - 
ERROR - Reduce instance aborted.
```

**Comment by KathleenLabrie** [comment]
Alright, got something reasonable to reproduce the error.

Data: https://drive.google.com/drive/folders/1bsTJjL9TwNx_ck_VNELInbCbwqwtPA5U?usp=sharing

Recipe:
```
def debug(p):
    p.detectSources(p)
    p.adjustWCSToReference(p)
```

Run:  `reduce -r debug.debug *_skyCorrected.fits

`release/3.1.x`.   Both Mac OS X and Linux.

**Comment by chris-simpson** [comment]
This just requires a check that there are some sources before trying to match them so I've added that. I'm unclear as to why it *didn't* crash when you started with the `_astrometryCorrected.fits` files. Pushed to `release/3.1.x` and cherry-picked into `master`.

**Comment by KathleenLabrie** [comment]
The logs were identical, up to the error message.   Number of sources, offsets measured.  It just didn't crash.

**Comment by chris-simpson** [comment]
I'm not sure i understand that but I'm not going to spend time working out why something *doesn't* crash :) so I'll close this
