### ISSUE TITLE
QECorrect crash on GMOS-N EEV data

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#422]
Branch: release/3.1.x

Some if block gets activated and expects a couple variables to be set which are not.  My gut feeling is that there's a problem getting some LUT values for the EEV, but I need to look further into it.  Here's the error trace with a couple "KLDEBUG" showing that `scalings` and `scaling_samples` are not filled in.  It's either that they need values or the if block where they are used should not be activated.

```
   PRIMITIVE: QECorrect
   --------------------
   N20110313S0188_fringeCorrected.fits needs no correction as it does not have the Hamamatsu CCDs
KLDEBUG: scalings= []
KLDEBUG: scaling_samples= []
ERROR - Traceback (most recent call last):
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/reduction/coreReduce.py", line 238, in runr
ERROR -     primitive_as_recipe()
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 364, in gn
ERROR -     ret_value = fn(pobj, adinputs=adinputs, **fnargs)
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 293, in gn
ERROR -     ret_value = fn(pobj, **kwargs)
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/geminidr/gmos/primitives_gmos_image.py", line 559, in QECorrect
ERROR -     scale_factors = 1 / np.average(
ERROR -   File "<__array_function__ internals>", line 180, in average
ERROR -   File "/Users/klabrie/condaenvs/susd3.9_20220816/lib/python3.9/site-packages/numpy/lib/function_base.py", line 547, in average
ERROR -     raise ZeroDivisionError(
ERROR - ZeroDivisionError: Weights sum to zero, can't be normalized
ERROR - Weights sum to zero, can't be normalized
ERROR - reduce caught an unhandled exception.
ERROR - 
ERROR - Weights sum to zero, can't be normalized
ERROR - Traceback (most recent call last):
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/scripts/reduce", line 87, in main
ERROR -     r_reduce.runr()
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/reduction/coreReduce.py", line 238, in runr
ERROR -     primitive_as_recipe()
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 364, in gn
ERROR -     ret_value = fn(pobj, adinputs=adinputs, **fnargs)
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 293, in gn
ERROR -     ret_value = fn(pobj, **kwargs)
ERROR -   File "/Users/klabrie/data/GemKLRepo/activedragons/geminidr/gmos/primitives_gmos_image.py", line 559, in QECorrect
ERROR -     scale_factors = 1 / np.average(
ERROR -   File "<__array_function__ internals>", line 180, in average
ERROR -   File "/Users/klabrie/condaenvs/susd3.9_20220816/lib/python3.9/site-packages/numpy/lib/function_base.py", line 547, in average
ERROR -     raise ZeroDivisionError(
ERROR - ZeroDivisionError: Weights sum to zero, can't be normalized
ERROR - 
ERROR - Reduce instance aborted.
```

To reproduce:  `reduce -r QECorrect N20110313S0188_fringeCorrected.fits`
File available at: https://drive.google.com/drive/folders/10uYdiUZAwBU49DddJo9_GISXfBYWHyej?usp=share_link

**Comment by KathleenLabrie** [comment]
Looks like a simple overlook of what would happen when the QE correction was not needed for non-Hamamatsu's.

The Ham vs others is handle correctly in the first for-loop but then the if-block that follows assumes that some files needed correction.  A simple check whether any files were found to need correction to that if-block ensure that it is entered only if at least one file required the correction.
