### ISSUE TITLE
Strange crash in determineAstrometricSolution - negative dimension

### ISSUE THREAD

**Issue by KathleenLabrie** [GeminiDRSoftware/DRAGONS#447]
One file from GMOS-S new 2023 CCDs crashes in `determineAstrometricSolution`.   Branch: `release/3.2.x` commit: 23fb519d3c.

To reproduce:
`reduce -r determineAstrometricSolution S20231223S0118_refcatAdded.fits`

File in: https://drive.google.com/drive/folders/1dMvTHqCUJmIhv_RgWzzq3VaVZqOmnpxs?usp=drive_link   (NOIRLab Staff only)

The trace: 
```
   Aligning S20231223S0118_refcatAdded.fits extension 9 with 1 REFCAT and 10 OBJCAT sources
ERROR - Traceback (most recent call last):
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/reduction/coreReduce.py", line 240, in runr
ERROR -     primitive_as_recipe()
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 352, in gn
ERROR -     ret_value = fn(pobj, adinputs=adinputs, **fnargs)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 269, in gn
ERROR -     ret_value = fn(pobj, **kwargs)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/geminidr/core/primitives_register.py", line 420, in determineAstrometricSolution
ERROR -     transform = fit_model(m_init,
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/gempy/library/matching.py", line 515, in fit_model
ERROR -     m_init = fit_it(model, xin, xout, scale=scale, sigma=sigma)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/gempy/library/matching.py", line 177, in __call__
ERROR -     landscape = self.mklandscape(ref_coords, sigma*scale, maxsig, landshape)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/gempy/library/matching.py", line 112, in mklandscape
ERROR -     landscape = np.zeros(landshape)
ERROR - ValueError: negative dimensions are not allowed
ERROR - negative dimensions are not allowed
ERROR - reduce caught an unhandled exception.
ERROR - 
ERROR - negative dimensions are not allowed
ERROR - Traceback (most recent call last):
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/scripts/reduce", line 87, in main
ERROR -     r_reduce.runr()
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/reduction/coreReduce.py", line 240, in runr
ERROR -     primitive_as_recipe()
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 352, in gn
ERROR -     ret_value = fn(pobj, adinputs=adinputs, **fnargs)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/recipe_system/utils/decorators.py", line 269, in gn
ERROR -     ret_value = fn(pobj, **kwargs)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/geminidr/core/primitives_register.py", line 420, in determineAstrometricSolution
ERROR -     transform = fit_model(m_init,
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/gempy/library/matching.py", line 515, in fit_model
ERROR -     m_init = fit_it(model, xin, xout, scale=scale, sigma=sigma)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/gempy/library/matching.py", line 177, in __call__
ERROR -     landscape = self.mklandscape(ref_coords, sigma*scale, maxsig, landshape)
ERROR -   File "/home/kathleen.labrie/data/GemKLRepo/activedragons/gempy/library/matching.py", line 112, in mklandscape
ERROR -     landscape = np.zeros(landshape)
ERROR - ValueError: negative dimensions are not allowed
```

**Comment by chris-simpson** [comment]
I think this needs better logic when there aren't many sources in the reference catalogue. Or perhaps it just needs to create an image which is a few pixels larger than the bounds of the reference catalogue in each dimension.
