### ISSUE TITLE
Error when accessing `standardizeSpectralFormat` params for BIAS data for GHOST via `showpars`

### ISSUE THREAD

**Issue by davner** [GeminiDRSoftware/DRAGONS#467]
An error occurs when attempting to access the `standardizeSpectralFormat` primitive params using a bias file for the GHOST instrument via the CLI tool `showpars`. The issue does not arise with other primitives like `standardizeStructure`.

### Steps to reproduce

I have `DRAGONS` installed from the `master` branch. 

Test file: `S20240511S0046_blue002.fits`

```console
$ showpars S20240511S0046_blue002.fits standardizeSpectralFormat
Dataset tagged as {'BIAS', 'GEMINI', 'GHOST', 'CAL', 'UNPREPARED', 'BLUE', 'SOUTH', 'RAW'}

Traceback (most recent call last):
  File "/Users/dan.avner/miniconda3/envs/goats-env/bin/showpars", line 78, in <module>
    sys.exit(main())
  File "/Users/dan.avner/miniconda3/envs/goats-env/bin/showpars", line 36, in main
    return showpars(pobj, args.primitive, tags, args.doc)
  File "/Users/dan.avner/miniconda3/envs/goats-env/bin/showpars", line 59, in showpars
    raise KeyError(f"{primname} doesn't exist for "
KeyError: "standardizeSpectralFormat doesn't exist for this data type."
```

**Comment by chris-simpson** [comment]
Only just seen this, sorry.

`standardizeSpectralFormat` runs on a file after the fibre spectra have been extracted (it changes the way the data are stored i the AstroData object so that it's in a friendlier format when written as a FITS file). It is therefore not available for a bias frame (in the same way that the photometry primitives aren't available for spectra or the wavelength calibration primitive is not available for an image). So the behaviour is correct.
